/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 scene.gltf 
Author: ᗩᒪE᙭. Kᗩ.🚗 (https://sketchfab.com/Alex.Ka.)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/bmw-m3-gtr-e46-street-acschnitzer-blackedition-7f060f9d44b74c34a5184399a6cfc6d7
Title: BMW M3 GTR E46 Street ACschnitzer BlackEdition
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.ACschnitzer} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.BMW_M3_GTR_E46_Street_ACschnitzer_BlackEdition_by_Alex_Ka} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.back} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.blackaluminium} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.blackchrome} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.blackmatte} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.blackplastic} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.bodyblack} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.bottom} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.brakedisc} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.carshadow} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.detailschrome} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.detailsmatte} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.detailsplastic} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.emblem} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.exaustbronze} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.exaustcarbon} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.exaustchrome} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.exhausthole} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.floor} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.grill1} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.grill2} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.grill3} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.grill4} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.handle} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.headP} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.headlight} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.headlightglass} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.interior} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.logoakrapovic} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.mats} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.midbrakelight} />
        <mesh geometry={nodes.Object_35.geometry} material={materials.mirror} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.nurburgring} />
        <mesh geometry={nodes.Object_37.geometry} material={materials.plateF} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.plateR} />
        <mesh geometry={nodes.Object_39.geometry} material={materials.platelamps} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.platelogo} />
        <mesh geometry={nodes.Object_41.geometry} material={materials.plateredlamp} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.playboy} />
        <mesh geometry={nodes.Object_43.geometry} material={materials.radiator} />
        <mesh geometry={nodes.Object_44.geometry} material={materials.radiatorgrillblack} />
        <mesh geometry={nodes.Object_45.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_46.geometry} material={materials.rim2} />
        <mesh geometry={nodes.Object_47.geometry} material={materials.rimbolts} />
        <mesh geometry={nodes.Object_48.geometry} material={materials.rimlogo} />
        <mesh geometry={nodes.Object_49.geometry} material={materials.sideturn1} />
        <mesh geometry={nodes.Object_50.geometry} material={materials.sideturn2} />
        <mesh geometry={nodes.Object_51.geometry} material={materials.stitch} />
        <mesh geometry={nodes.Object_52.geometry} material={materials.suport} />
        <mesh geometry={nodes.Object_53.geometry} material={materials.taillight} />
        <mesh geometry={nodes.Object_54.geometry} material={materials.tireprotector} />
        <mesh geometry={nodes.Object_55.geometry} material={materials.tireside} />
        <mesh geometry={nodes.Object_56.geometry} material={materials.windoF} />
        <mesh geometry={nodes.Object_57.geometry} material={materials.windoR} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
